export const channel = {
  store: {
    getSettings: "settings:get",
    setSettings: "settings:set",
    clearSettings: "settings:clear",
    get: "store:get",
    set: "store:set",
    clear: "store:clear",
  },
  dialog: {
    selectDirectory: "dialog:select-directory",
    showFileInFolder: "dialog:show-file-in-folder",
    selectFile: "dialog:select-file",
    openDirectory: "dialog:open-directory",
    openExternal: "dialog:open-external",
  },
  font: {
    getFonts: "font:get-fonts",
  },
  file: {
    getSize: "file:get-size",
  },
  download: {
    getList: "download:get-list",
    getDownloadData: "download:get-download-data",
    add: "download:add",
    addList: "download:add-list",
    pause: "download:pause",
    resume: "download:resume",
    cancel: "download:cancel",
    retry: "download:retry",
    sync: "download:sync",
    clear: "download:clear",
  },
  lyrics: {
    searchNeteaseSongs: "lyrics:netease-search",
    getNeteaseLyrics: "lyrics:netease-lyrics",
    searchLrclib: "lyrics:lrclib-search",
  },
  live: {
    getAudioPlayUrls: "live:get-audio-play-urls",
    danmakuSubscribe: "live:danmaku-subscribe",
    danmakuClose: "live:danmaku-close",
    danmakuMessage: "live:danmaku-message",
    danmakuStatus: "live:danmaku-status",
  },
  tts: {
    listWindowsVoices: "tts:list-windows-voices",
    synthesizeWindows: "tts:synthesize-windows",
    listSapiVoices: "tts:list-sapi-voices",
    synthesizeSapi: "tts:synthesize-sapi",
    parseNaturalVoicePackage: "tts:parse-natural-voice-package",
    installNaturalVoiceAdapter: "tts:install-natural-voice-adapter",
  },
  router: {
    navigate: "router:navigate",
  },
  http: {
    get: "http:get",
    post: "http:post",
  },
  player: {
    state: "player:state",
    prev: "player:prev",
    next: "player:next",
    toggle: "player:toggle",
  },
  shortcut: {
    triggered: "shortcut:triggered",
    register: "shortcut:register",
    unregister: "shortcut:unregister",
    registerAll: "shortcut:register-all",
    unregisterAll: "shortcut:unregister-all",
  },
  app: {
    getVersion: "app:get-version",
    checkUpdate: "app:check-update",
    onUpdateAvailable: "app:on-update-available",
    downloadUpdate: "app:download-update",
    updateMessage: "app:update-message",
    quitAndInstall: "app:quit-and-install",
    openInstallerDirectory: "app:open-installer-directory",
    onBeforeQuit: "app:on-before-quit",
    isDev: "app:is-dev",
    setProxySettings: "app:set-proxy-settings",
  },
  cookie: {
    get: "cookie:get",
    set: "cookie:set",
  },
  localMusic: {
    scan: "local-music:scan",
    deleteFile: "local-music:delete-file",
  },
  window: {
    toggleMini: "window:toggle-mini",
    minimize: "window:minimize",
    toggleMaximize: "window:toggle-maximize",
    close: "window:close",
    maximize: "window:maximize",
    unmaximize: "window:unmaximize",
    isMaximized: "window:is-maximized",
    enterFullScreen: "window:enter-full-screen",
    leaveFullScreen: "window:leave-full-screen",
    isFullScreen: "window:is-full-screen",
    toggleDevTools: "window:toggle-dev-tools",
  },
};
